spring.application.name=sima

# Configuración de WhatsApp Cloud API
whatsapp.api.url=https://graph.facebook.com/v21.0/
whatsapp.api.token=EAA... (tu token larguísimo aquí)
whatsapp.api.phone-number-id=1099xxxxxxxxxxx